### PR TITLE
uat: switch to tasty-tmux

### PR DESCRIPTION
**Pull request by frasertweedale**
This commit switches to tasty-tmux and also chases the API changed caused by PR
https://github.com/purebred-mua/tasty-tmux/pull/10.  (Hence, do not merge this
until that tasty-tmux PR gets merged).

### CODE REVIEW

**Comment by frasertweedale** [comment]
I'll resolve the conflicts and merge after I cut a tasty-tmux release on hackage.

**Comment by romanofski** [comment]
Sweet. Go ahead. I'll patch up the nix side of things afterwards.

**Comment by frasertweedale** [comment]
OK so the problem now is lossy `OverloadedStrings` conversion to `ByteString` where we have unicode chars in patterns.  We'll have to inject a dose of "encodeUtf8" in a couple of places.  Bit nasty and surprising behaviour, should think about how to address that in *tasty-tmux*.

**Comment by romanofski** [comment]
I'll fix up the nix side later tonight.

**Pull request merged**
