### PR TITLE
Add video to show off Purebred

### PR DESCRIPTION
**Pull request by romanofski**
```
commit 10a5a5c7682482a86ed870fbde378aeff5817160
Author: Róman Joost <roman@bromeco.de>
Date:   Sat May 29 16:02:37 2021 +1000

    docs: markdown fixes/clean ups for the README

commit d303fe510bcfc50025f70f274bd17d8a1ddbe575
Author: Róman Joost <roman@bromeco.de>
Date:   Sat May 29 15:59:37 2021 +1000

    docs: Add a video to show off Purebred in the README
    
    Helps to get a better picture of what it Purebred currently looks like
    than just a screen shot. Perhaps more will join with the project.
```

### CODE REVIEW

**Review by frasertweedale — CHANGES_REQUESTED** [review]
@romanofski I like the idea very much, but I don't like this particular gif.  In particular:

- The gif is too tall.  Mostly empty lines taking vertical space for no benefit.
- The quality is poor.  In particular, text in highlighted row of List widget is unreadable

**Comment by romanofski** [comment]
> @romanofski I like the idea very much, but I don't like this particular gif. In particular:
> 
>     * The gif is too tall.  Mostly empty lines taking vertical space for no benefit.
> 
>     * The quality is poor.  In particular, text in highlighted row of List widget is unreadable

Yeah I get you. I see if I can try another recording and get better quality. I wish I could include a `webp` format instead of a `gif` tho.

**Comment by romanofski** [comment]
I hope this one is better. I've increased the font size as well so that the dithering doesn't stuff up too much.

**Comment by frasertweedale** [comment]
That's much improved.  But please replace the gif in the initial commit.  As it is, the first commits adds the older 1MB .gif, then the second commit replaces it with another 1.3MB .gif.

**Comment by romanofski** [comment]
Ah thanks for picking this up. I merged it with the wrong commit. Fixed both commits  up now.

**Comment by frasertweedale** [comment]
I'm a fan of not carry more big blobs in the repo than necessary :)

**Pull request merged**
