### PR TITLE
Fix/nix include purebred icu

### PR DESCRIPTION
**Pull request by romanofski**

### CODE REVIEW

**Comment by frasertweedale** [comment]
I mean... I dunno if forcing use of *purebred-icu* is a solution.  We can't do it for every conceivable plugin...

But I don't mind if you merge this, since I don't use nix yet :)

**Comment by romanofski** [comment]
Hm.. I actually don't know why travis is not running any tests o.O

In regards to forcing the plugin... I guess ideally we should perhaps be using multiple configs instead of a single one. That way there is no need of always enabling it. Alternatively move some of this testing into purebred-icu since we have the UAT framework in a separate package.

**Comment by romanofski** [comment]
Let's sit on this one for a bit. I might just keep the nix changes, but not enable it globally. Because you're right: can't do it for all.

**Comment by romanofski** [comment]
I removed the changes to our tests and CI. Made the purebred-icu integration optional, which can be enabled with an argument to `nix-shell` or `nix-build`.

**Pull request merged**
