### PR TITLE
Incorporate attachments editor

### PR DESCRIPTION
**Pull request by romanofski**
This is it. This adds the file browser with the ability to add attachments, re-edit the mail body, as well as delete the attachments again.

There is still massive room for improvement (e.g. toggling hidden directories or filtering for files), but I thought the current state is a good starting point.

### CODE REVIEW

**Comment by frasertweedale** [comment]
Awsm... no idea when I have time to review this.  But well done, I'm looking forward to it :D

**Comment by romanofski** [comment]
You could also just quickly fly over it and wave it through. We refactor anything later?

**Comment by romanofski** [comment]
You enjoy yourself mate. Not in a hurry. Will find something else.

**Comment by frasertweedale** [comment]
OK, I've eyeballed and tested the patch.  Just a few comments.  Not necessarily blockers, just want to get your feedback on these points and then we can prepare to merge.

1. use of `decodeUtf8` in one of the patches.  Should replace with a total function.
2. attachment viewer and file chooser keybindings are not shown in help
3. default keybindings do not offer a way to invoke "help" view from the attachment view or file chooser
4. attachments are *prepended* to the attachment list.  I'd expect appending.
5. When selecting multiple attachments, ideally there should be different indications for "selected" and "current item".  Maybe a checkbox type thing; there must be unicode glyphs for empty/checked boxes.  But apart from that the multi-file selection feature works well.  I was impressed!

**Comment by romanofski** [comment]
Cheers for the review. Indeed there are some changes needed. I'll implement and update.

**Comment by romanofski** [comment]
Oh.. I'm just realising one thing tho, that is the invokation of the help from the attachments or file browser. It's just a missing keybinding to switch to the help view, but currently there is no way to go "back". Suppose for that to work we do need to keep the views on a stack or tree to know where to go back to. So I'll have to defer that...

**Comment by frasertweedale** [comment]
@romanofski there are some conflicts with the other PRs that were recently merged.

**Comment by frasertweedale** [comment]
@romanofski ok no worries, we can defer the activation of help view.  I'd still like to see the keybindings in the help view though, so (1) (2) and (4) are the items I'd like addressed before we merge.

**Comment by romanofski** [comment]
Yeah absolutely. I've actually found another bug which I'll also fix with an additional test.

**Comment by romanofski** [comment]
Alright here we go. I hope I haven't forgotten anything. I choose the checkbox idea. Thought it looked spiffy.

**Comment by frasertweedale** [comment]
ACK.  In my terminal font the glyphs for selected/not selected checkbox are not very pretty but this is a minor issue.  Maybe we can make it configurable in the future.  Not a blocker.  My requests were addressed.  Merge ho!

**Pull request merged**
