### PR TITLE
Take length of needle outside of go

### PR DESCRIPTION
**Pull request by mlang**

### CODE REVIEW

**Comment by frasertweedale** [comment]
Hi @mlang, thanks for your PR.  Could you please explain why this change is needed?

**Comment by romanofski** [comment]
Was wondering whether it would help fix #448 but had no time to look into it yet. Perhaps will have a bit of time this week.

**Comment by frasertweedale** [comment]
ping @mlang - are you able to provide some context for this PR?

**Comment by frasertweedale** [comment]
ping @mlang again - can you explain what motivated this change?

**Comment by romanofski** [comment]
I close it for now. Happy to reopen :)

**Pull request closed without merging**
